<?php

namespace SoftUniBlogBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;
use SoftUniBlogBundle\Entity\Article;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em,
                                Mapping\ClassMetadata $metaData = null)
    {
        parent::__construct($em,
            $metaData == null ? new Mapping\ClassMetadata(Article::class) :
                $metaData);
    }

    /**
     * @param Article $article
     * @return bool
     * @throws ORMException
     */
    public function insert(Article $article)
    {
        try {
            $this->_em->persist($article);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Article $article
     * @return bool
     * @throws ORMException
     */
    public function update(Article $article)
    {
        try {
            $this->_em->merge($article);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Article $article
     * @return bool
     * @throws ORMException
     */
    public function remove(Article $article)
    {
        try {
            $this->_em->remove($article);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }
}
